# Generated by Django 2.2.4 on 2019-09-24 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('procurement_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusType',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('update', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('vendor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=50)),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('address3', models.TextField()),
                ('city', models.TextField(max_length=100)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('vendor_contact_rep', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('update', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='product_details',
            name='updated_by',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='product_details',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('req_id', models.AutoField(primary_key=True, serialize=False)),
                ('req_title', models.CharField(max_length=100)),
                ('req_prod_quantity', models.IntegerField()),
                ('req_due_date', models.DateField()),
                ('req_comments', models.TextField()),
                ('requester_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('update', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('req_product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.Product_details')),
                ('req_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.StatusType')),
            ],
        ),
        migrations.CreateModel(
            name='ProcurementFulfillment',
            fields=[
                ('proc_ful_id', models.IntegerField(primary_key=True, serialize=False)),
                ('proc_order_date', models.DateField()),
                ('proc_prod_order_quantity', models.IntegerField()),
                ('proc_ful_comments', models.TextField()),
                ('proc_ful_cost', models.IntegerField()),
                ('requester_id', models.IntegerField()),
                ('req_requester_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=50)),
                ('update', models.DateTimeField(null=True)),
                ('updated_by', models.CharField(max_length=50)),
                ('proc_prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.Product_details')),
                ('proc_req_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.ProcurementRequest')),
                ('proc_vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.VendorDetails')),
                ('req_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procurement_app.StatusType')),
            ],
        ),
    ]
